name: Keep Streamlit Alive

# Triggers: schedule every 5 minutes + manual trigger
on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:        # allows manual trigger

jobs:
  ping_streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Main Streamlit App
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://ecorouteai-czqtu2dtwxkqedsadlxhcm.streamlit.app/)
          echo "Main page response code: $RESPONSE"

      - name: Ping User App Page
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://ecorouteai-czqtu2dtwxkqedsadlxhcm.streamlit.app/User.App)
          echo "User App page response code: $RESPONSE"

      - name: Ping City Planner Page
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://ecorouteai-czqtu2dtwxkqedsadlxhcm.streamlit.app/City_Planner)
          echo "City Planner page response code: $RESPONSE"
