name: Keep Streamlit Alive

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  ping_streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit App
        run: |
          curl -X GET https://your-username-your-app-name.streamlit.app
